:linkcss:
//:copycss:
:stylesheet: style.css
:toc:

= i3b

Buce's window manager scripts and configs.

== Install

There's an link:https://aur.archlinux.org/packages/i3b[AUR package] for Arch Linux
and a Makefile for other distros.
In addition, many of the scripts can be installed standalone
by dropping them in your `$PATH` and making them executable.

== Requirements

* i3blocks-monit: bash, monit
* i3blocks-pickdate: bash, pickdate
* i3move: perl, xrandr, xdotool
* i3scratchmark: bash, jq
* pickdate: rofi, cal, awk
* rofi-blezz: bash, rofi, rofi-blezz, sed

== Description

=== i3move

Move a floating i3 window.

Demo: https://i.imgur.com/IVnZ9fS.mp4

Documentation: https://dmbuce.github.io/i3b/i3move.1.html

Quick Start: https://dmbuce.github.io/i3b/i3move.1.html#EXAMPLES

== i3scratchmark

Manage i3 scratchpad windows with marks.

Documentation: https://github.com/DMBuce/i3b/blob/master/doc/i3scratchmark.1.txt

== pickdate

A simple rofi date picker.

!link:https://i.imgur.com/TCnCXKU.png[Screenshot]

Documentation: https://github.com/DMBuce/i3b/blob/master/doc/pickdate.1.txt

== i3blocks-pickdate

Use `pickdate` as a dropdown calendar in i3blocks.

Documentation: https://github.com/DMBuce/i3b/blob/master/doc/i3blocks-pickdate.1.txt

== rofi-blezz

Run link:https://github.com/davatorium/rofi-blezz[rofi's blezz module]
with a different starting menu.
Similar to link:https://github.com/Blezzing/blezz[blezz's] `-d` option,
this is a workaround for rofi's blezz module not having such functionality.

Documentation: https://github.com/DMBuce/i3b/blob/master/doc/rofi-blezz.1.txt

== i3blocks-monit

Add link:https://mmonit.com/monit/[monit] services summary to i3blocks.

Default Look: https://i.imgur.com/1pK873k.png

Custom Labels: https://i.imgur.com/HuStDiw.png

Minimal: https://i.imgur.com/Ki0SCD5.png

Documentation: https://github.com/DMBuce/i3b/blob/master/doc/i3blocks-monit.1.txt

// vim: set syntax=asciidoc:
